CXX_WARN_FLAGS=-Wall -Wfloat-equal -Wshadow -pedantic -std=c++98
IFLAGS+=-I../${SOLVER_DIR}/include -I../${IGM_DIR}/include


ifdef DEBUG
DEBUGFLAGS=DEBUG=1
CXXFLAGS=-g -DSMPCS_DEBUG=1 ${CXX_WARN_FLAGS} ${IFLAGS}
CMAKEFLAGS=-DCMAKE_BUILD_TYPE=DEBUG
else
DEBUGFLAGS=
CXXFLAGS+=-O3 ${CXX_WARN_FLAGS} ${IFLAGS}
CMAKEFLAGS=-DCMAKE_BUILD_TYPE=Release
endif


